# https://taskfile.dev
version: '3'
vars:
  BINFILE: ssftp

tasks:
  default:
    # dir: src
    cmds:
      - CGO_ENABLED=0 go build .
      - upx "{{.BINFILE}}"
    # silent: true
    method: checksum
    generates:
      - "{{.BINFILE}}"

  build-windows:
    # dir: src
    cmds:
      - CGO_ENABLED=0 GOOS=windows go build .
      - upx "{{.BINFILE}}.exe"
    # silent: true
    method: checksum
    generates:
      - "{{.BINFILE}}.exe"

  tests-linux:
    dir: tests/linux
    cmds:
      - ./run-tests.sh

  tests-windows:
    deps:
      - build-windows
    cmds:
      - mv ssftp.exe tests/windows
      - curl -L https://github.com/ovh/venom/releases/download/v1.0.1/venom.windows-amd64 -o tests/windows/venom.exe

  
  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean